# Site settings
title: Angulo Ceramic Art
email: info@anguloceramicart.com
description: ~
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.anguloceramicart.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
