# Site settings
title:       Angulo Ceramic Art
email:       info@anguloceramicart.com
description: ~
baseurl:     ''
url:         http://www.anguloceramicart.com

# Build settings
markdown: kramdown

# Other settings
safe: true # Forced by GitHub pages
lsi: false # Forced by GitHub pages
